image: registry.gitlab.com/aleksandr-kotlyar/gitlab-allure-history:v3

stages:
  - test
  - report

variables:
  ENV: 'stage'

test:
  stage: test
  allow_failure: true
  script:
    pytest tests
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - allure-results

allure:
  stage: report
  script:
    - git clone --single-branch --branch gl-pages $CI_PROJECT_URL

    - REPORT=job_${CI_PIPELINE_ID}
    - LAST=$("cd ${CI_PROJECT_NAME}/public/${ENV}/${CI_COMMIT_REF_NAME}; ls -td -- */ | head -n 1") || echo "No history"
    - cp -r ${LAST}history allure-results || echo "No history"
    - allure generate allure-results -o $REPORT
    - mkdir -p ${CI_PROJECT_NAME}/public/${ENV}/${CI_COMMIT_REF_NAME}
    - cp -r $REPORT ${CI_PROJECT_NAME}/public/${ENV}/${CI_COMMIT_REF_NAME}

    - cd $CI_PROJECT_NAME
    - git config user.name "Gitlab Runner"
    - git config user.email ${CI_EMAIL}
    - git remote add $CI_PROJECT_NAME https://oauth2:${ALLURE_GITLAB_PAGES}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git
    - git add ./public
    - git commit -m "pipeline_${CI_PIPELINE_ID}_job_${CI_JOB_ID}"
    - git push -u $CI_PROJECT_NAME
  artifacts:
    when: on_success
    expire_in: 3 days
    paths:
      - public
