include:
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/gitlab-allure-history@$CI_COMMIT_TAG
    inputs:
      allure-history-image-tag: $CI_COMMIT_TAG
      build-runtime-image: "true"
      comment-mr: "false"
    rules:
      - if: $CI_COMMIT_TAG
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/gitlab-allure-history@$CI_COMMIT_SHA
    inputs:
      allure-history-image-tag: "2026.2.8"
      comment-mr: "true"
    rules:
      - if: $CI_COMMIT_TAG == null

default:
  image: $ALLURE_HISTORY_IMAGE

test_gate:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: never
    - if: $CI_PIPELINE_SOURCE != "web"
      when: always
  script:
    - set -euo pipefail
    - echo "$CI_JOB_ID" > jobid
    - pytest -m "not demo" --env="$ENV" --junitxml=report-gate.xml
  artifacts:
    when: always
    expire_in: 2 hours
    paths:
      - allure-results
      - jobid
      - report-gate.xml

test_demo:
  stage: test
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: never
    - if: $CI_PIPELINE_SOURCE != "web"
      when: always
  script:
    - set -euo pipefail
    - pytest -m "demo" --env="$ENV" --junitxml=report-demo.xml
  artifacts:
    when: always
    expire_in: 2 hours
    paths:
      - allure-results
      - report-demo.xml

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never
  script:
    - echo "Creating release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG of the gitlab-allure-history component."
