image: registry.gitlab.com/aleksandr-kotlyar/gitlab-allure-history:v3

stages:
  - test
  - report

test:
  stage: test
  allow_failure: true
  script:
    pytest tests
  artifacts:
    when: always
    paths:
      - allure-results

allure:
  stage: report
  script:
    - git clone --single-branch --branch gl-pages $CI_PROJECT_URL
    - REPORT=job_${CI_PIPELINE_ID}
    - LAST=$("cd ${CI_PROJECT_NAME}/public/stage; ls -td -- */ | head -n 1") || echo "No history"
    - cp -r ${LAST}history allure-results || echo "No history"
    - allure generate allure-results -o $REPORT
    - cp -r $REPORT ${CI_PROJECT_NAME}/public/stage

    - cd $CI_PROJECT_NAME
    - git config user.name "Gitlab Runner"
    - git config user.email ${CI_EMAIL}
    - git add public/stage
    - git commit -m "pipeline_${CI_PIPELINE_ID}_job_${CI_JOB_ID}"
    - git push -u
  artifacts:
    when: on_success
    paths:
      - $REPORT
