image: registry.gitlab.com/aleksandr-kotlyar/gitlab-allure-history:v4

stages:
  - test
  - report
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME != "gl-pages"

test:
  stage: test
  allow_failure: true
  script:
    - echo "${CI_JOB_ID}" > jobid
    - pytest tests
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - allure-results
      - jobid

allure:
  stage: report
  script:
    - git clone --single-branch --branch gl-pages $CI_PROJECT_URL

    - JOB_ID=$(cat jobid)
    - REPORT=job_${JOB_ID}
    - CURRENT_BRANCH=${CI_PROJECT_NAME}/public/${CI_COMMIT_REF_NAME}
    - LAST=${CURRENT_BRANCH}/$(cd ${CURRENT_BRANCH}; ls -td -- */ | head -n 1)
    - cp -r ./${LAST}history allure-results || echo "No history"

    #echo "executor.json"
    - echo '{"name":"GitLabCI","type":"gitlab","reportName":"Allure Report with history",' > executor.json
    - echo "\"url\":\"${CI_PAGES_DOMAIN}/${CURRENT_BRANCH}\"," >> executor.json
    - echo "\"reportUrl\":\"${CI_PAGES_DOMAIN}/${CURRENT_BRANCH}/${REPORT}/\"," >> executor.json
    - echo "\"buildUrl\":\"${CI_PIPELINE_URL}\"," >> executor.json
    - echo "\"buildName\":\"GitLab Job Run `#`${JOB_ID}\",\"buildOrder\":\"${JOB_ID}\"}" >> executor.json
    #cat executor.json
    - mv ./executor.json ./allure-results

    - allure generate allure-results -o $REPORT

    - mkdir -p ${CURRENT_BRANCH}
    - cp -r $REPORT ${CURRENT_BRANCH}
    - cp -r ${CI_PROJECT_NAME}/public ./public

    - cd $CI_PROJECT_NAME
    - git config user.name "Gitlab Runner"
    - git config user.email ${CI_EMAIL}
    - git remote add $CI_PROJECT_NAME https://oauth2:${ALLURE_GITLAB_PAGES}@${CI_REPOSITORY_URL}
    - git add ./public
    - git commit -m "pipeline_${CI_PIPELINE_ID}_job_${CI_JOB_ID}"
    - git push -u $CI_PROJECT_NAME
  after_script:
    - >
      curl --request POST --header "PRIVATE-TOKEN: ${PRIVATE_API_TOKEN}"
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipeline?ref=gl-pages"

pages:
  image: python:3.7-alpine
  stage: deploy
  script:
    - python3 generate_index.py public
    - python3 generate_index.py public/${CI_COMMIT_REF_NAME}
  rules:
    - if: $CI_COMMIT_REF_NAME == 'gl-pages'
  artifacts:
    paths:
      - public
