image: registry.gitlab.com/aleksandr-kotlyar/gitlab-allure-history:v3

stages:
  - test
  - report

test:
  stage: test
  allow_failure: true
  script:
    pytest tests
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - allure-results

allure:
  stage: report
  script:
    - git clone --single-branch --branch gl-pages $CI_PROJECT_URL
    - cp -r ${CI_PROJECT_NAME}/public public
    - REPORT=job_${CI_PIPELINE_ID}
    - LAST=$("cd public/stage; ls -td -- */ | head -n 1") || echo "No history"
    - cp -r ${LAST}history allure-results || echo "No history"
    - allure generate allure-results -o $REPORT
    - cp -r $REPORT public/stage
  artifacts:
    when: on_success
    expire_in: 3 days
    paths:
      - public
