image: registry.gitlab.com/aleksandr-kotlyar/gitlab-allure-history:v6

stages:
  - build
  - test
  - report

build:
  image: docker:29.3.1
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never
  services:
    - docker:29.3.1-dind
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

test_gate:
  stage: test
  script:
    - echo "${CI_JOB_ID}" > jobid
    - pytest -m "not demo" --junitxml=report-gate.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: never
    - if: $CI_PIPELINE_SOURCE != "web"
      when: always
  artifacts:
    when: always
    expire_in: 2 hours
    paths:
      - allure-results
      - jobid
      - report-gate.xml

test_demo:
  stage: test
  allow_failure: true
  script:
    - pytest -m "demo" --junitxml=report-demo.xml || true
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: never
    - if: $CI_PIPELINE_SOURCE != "web"
      when: always
  artifacts:
    when: always
    expire_in: 2 hours
    paths:
      - allure-results
      - report-demo.xml

allure:
  stage: report
  needs: ["test_gate"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: never
    - if: $CI_PIPELINE_SOURCE != "web"
      when: always

  script:
    - git clone --single-branch --branch gl-pages $CI_PROJECT_URL

    - JOB_ID=$(cat jobid)
    - REPORT=job_${JOB_ID}
    - CURRENT_BRANCH=${CI_PROJECT_NAME}/public/${CI_COMMIT_REF_NAME}
    - cp -r ./${CURRENT_BRANCH}/history allure-results || echo "No history"

    #echo "executor.json"
    - echo '{"name":"GitLabCI","type":"gitlab","reportName":"Allure Report with history",' > executor.json
    - echo "\"reportUrl\":\"${CI_PAGES_URL}/${CI_COMMIT_REF_NAME}/${REPORT}/\"," >> executor.json
    - echo "\"buildUrl\":\"${CI_PIPELINE_URL}\"," >> executor.json
    - echo "\"buildName\":\"GitLab Job Run ${JOB_ID}\",\"buildOrder\":\"${JOB_ID}\"}" >> executor.json
    #cat executor.json
    - mv ./executor.json ./allure-results

    - allure generate allure-results -o $REPORT

    - mkdir -p $CURRENT_BRANCH
    - cp -r $REPORT $CURRENT_BRANCH
    - cp -r ${REPORT}/history $CURRENT_BRANCH
    - cp -r generate_index.py $CI_PROJECT_NAME
    - cp -r prune_reports.py $CI_PROJECT_NAME
    - cd $CI_PROJECT_NAME
    - python3 prune_reports.py public/${CI_COMMIT_REF_NAME} 20
    - python3 generate_index.py public
    - python3 generate_index.py public/${CI_COMMIT_REF_NAME}

    - git config user.name "Gitlab Runner"
    - git config user.email ${CI_EMAIL}
    - git remote set-url origin "https://oauth2:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git add ./public
    - git commit -m "pipeline_${CI_PIPELINE_ID}_job_${CI_JOB_ID}" || echo "No changes to commit"
    - git push origin gl-pages
